### ISSUE TITLE
Autoinstall for satip detects wrong satip interface

### ISSUE THREAD

**Issue by LuigiDC** [yavdr/yavdr-ansible#1]
file: satip_facts.py between line 50-53
`try:
response = sock.recv(1000)
if response and "SERVER:" in response:
got_response = True`

Problem:
Checking response to literal 'SERVER' not explicit enough.
Other bridges like hue also responding to the broadcast request with 'SERVER' like:

` ht 80/description.xml\r\nSERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0\r\nhue-bridgeid:`

Possible solution:
Improve literal to a more specific one for satip cards.

**Comment by seahawk1986** [comment]
I updated satip_facts.py to be more specific - please check if this problem still occurs
