### ISSUE TITLE
kodi 17 because of wrong PPA in  yavdr-ansible/roles/yavdr-common/defaults/main.yml?

### ISSUE THREAD

**Issue by davie2000** [yavdr/yavdr-ansible#10]
When using yavdr-ansible Kodi 17 gets installed instead of Kodi 18.
I saw [here ](https://www.vdr-portal.de/forum/index.php?thread/131575-yavdr-ansible/&postID=1311994#post1311994) that Kodi 18 is available in "experimental-kodi".

So I think you could change this
```
branch: unstable
repositories:
  - 'ppa:yavdr/main'
  - 'ppa:yavdr/unstable-main'
  - 'ppa:yavdr/{{branch}}-vdr'
  - 'ppa:yavdr/{{branch}}-kodi'
- 'ppa:yavdr/{{branch}}-yavdr'
```
to that
```
...
  - 'ppa:yavdr/{{branch}}-main'
...
  - 'ppa:yavdr/experimental-kodi'
...
```
to automatically install Kodi 18 (and correct a small flaw).

Am I right?
If so, would you please be so kind and "correct" it?

**Comment by seahawk1986** [comment]
As stated in https://github.com/yavdr/yavdr-ansible#usage, please use the bionic branch, which already uses the experimental PPAs: https://github.com/yavdr/yavdr-ansible/blob/bionic/group_vars/all - master still contains stuff for Ubuntu 16.04

**Comment by flensrocker** [comment]
Is the branch for 16.04 in use by anyone? Maybe we should delete it...

**Comment by davie2000** [comment]
Sorry for that.
Probably Kodi 17 was installed because I was using an old branch then.
