### ISSUE TITLE
nvidia-340 does not have a service for nvidia-persistenced

### ISSUE THREAD

**Issue by tjaalton** [yavdr/yavdr-ansible#12]
The install fails if the newest nvidia driver the hw supports is nvidia-340 (like on GT218 ION), because it doesn't have a service for nvidia-persistenced:

TASK [yavdr-xorg : start nvidia-persistenced] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service nvidia-persistenced: host"}

**Comment by seahawk1986** [comment]
Good catch - this should be fixed by https://github.com/yavdr/yavdr-ansible/commit/b520bd4f3fe474e0a5e9da38e65000c01eb3a525

**Comment by seahawk1986** [comment]
I am closing this for now since there have not been any newer reports regarding this problem.
