### ISSUE TITLE
Please make Installation of osd2web-Plugin selectable in host_vars/localhost ...

### ISSUE THREAD

**Issue by davie2000** [yavdr/yavdr-ansible#14]
Hi!

In light of recent issues (memory leak) could you please make the installation of osd2web-plugin depending on users choice in host_vars/localhost. Similar as with vdr-epg-daemon and other plugins like osdteletext (IIRC).

For example I was not aware that osd2web was installed automatically and obviously even got activated (and was eating memory).
I know, I should have had a look at the last changes here, but I was lazy :)

Thanks in advance and thank you for your very good work with yaVDR and Ansible!

PS: Sorry, for not being able to provide a solution as a pull request.

**Comment by davie2000** [comment]
I tried to take osd2web out of yavdr-desktop and make an own role for it.
Hope it works! Please take a look at my pull request.

**Comment by seahawk1986** [comment]
osd2web hat mit https://github.com/yavdr/yavdr-ansible/pull/15 eine eigene Rolle.
