### ISSUE TITLE
Ìnstalling yavdr-network installs (unwanted) nfs-kernel-server

### ISSUE THREAD

**Issue by hpannenb** [yavdr/yavdr-ansible#19]
Hi, @seahawk1986 .

I discovered installing yavdr-network but commenting out nfs-server in `yavdr07.yml` still installs the nfs-server. 

It might be related to the default data existing in the role `yavdr-network/defaults/main.yml` which explicitly sets `install-nfs-server: true`.

see [here](https://github.com/yavdr/yavdr-ansible/blob/20fea1d6efea56c319b8fab001d74a70bbc062f7/roles/yavdr-network/defaults/main.yml#L5)

Regards,
Holger.

**Comment by seahawk1986** [comment]
The package `vdr-addon-avahi-linker` (wich is installed by the role `yavdr-network`) has a hard dependency on `nfs-kernel-server`. To allow for a client-only use (the basic idea behind the avahi-linker is to share recordings in a Mesh-linke fashion) it would be necessary to split this up into several packages.

The variable `install-nfs-server` is currently unused.

**Comment by hpannenb** [comment]
Ok. Understood.
