### ISSUE TITLE
Starting KODI from the 'DESKTOP' leads into GLib.Error

### ISSUE THREAD

**Issue by LuigiDC** [yavdr/yavdr-ansible#2]
Syslog Output Mesage.
Sep  3 18:58:40 J3455 vdr: [1249] desktop: starting "/usr/share/applications/kodi.desktop"
Sep  3 18:58:40 J3455 vdr: [1910] animator thread thread ended (pid=1249, tid=1910)
Sep  3 18:58:41 J3455 vdr[1249]: use_systembus
Sep  3 18:58:41 J3455 vdr[1249]: Traceback (most recent call last):
Sep  3 18:58:41 J3455 vdr[1249]:   File "/var/lib/vdr/plugins/desktop/starter", line 9, in <module>
Sep  3 18:58:41 J3455 vdr[1249]:     load_entry_point('yavdr-frontend==0.0.10', 'console_scripts', 'start-desktop')()
Sep  3 18:58:41 J3455 vdr[1249]:   File "/usr/lib/python3/dist-packages/yavdr_frontend/start_desktop.py", line 25, in start_desktop
Sep  3 18:58:41 J3455 vdr[1249]:     fe = bus.get('de.yavdr.frontend')
Sep  3 18:58:41 J3455 vdr[1249]:   File "/usr/lib/python3/dist-packages/pydbus/proxy.py", line 47, in get
Sep  3 18:58:41 J3455 vdr[1249]:     0, timeout_to_glib(timeout), None)
Sep  3 18:58:41 J3455 vdr[1249]: GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name de.yavdr.frontend was not provided by any .service files (2)

**Comment by seahawk1986** [comment]
Using the latest python3-yavdrfrontend package should place the required DBus policy in the correct folder.

**Comment by LuigiDC** [comment]
Python3-yavdrfrontend reached through apt-get.
