### ISSUE TITLE
install-yavdr-headless.sh fails

### ISSUE THREAD

**Issue by hpannenb** [yavdr/yavdr-ansible#32]
The installation of a headless VDR server - with means of default git provided config - fails with the following error:
```
TASK [vdr : vdr configuration | create keymacros.conf] *********************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

AnsibleUndefinedVariable: 'vdr_output_plugin' is undefined
```

**Comment by hpannenb** [comment]
The issue is related to this section of the `keymacros.conf` template:
```
{% if vdr_output_plugin == "vdr-plugin-xineliboutput" %}
User9     @xineliboutput Red 4   # toggle autocrop
{% elif vdr_output_plugin == "vdr-plugin-softhddevice" %}
User9     @softhddevice Blue 2 5 # toggle autocrop
{% endif %}
```

**Comment by seahawk1986** [comment]
The plugin depended check was introduced with https://github.com/yavdr/yavdr-ansible/commit/00d4292ba19491eeaa58931dfbd33ebb2871e64e - https://github.com/yavdr/yavdr-ansible/commit/7ff6df2272cec5473f2482057c565fb0e563ab06 should fix it.

**Comment by hpannenb** [comment]
Works as supposed to. Thanks.
